# Generated by Django 4.1.6 on 2023-06-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='emblem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/emblems'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='VolleyballTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SCSapp.team')),
                ('competition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCSapp.volleyballcompetition')),
            ],
            options={
                'verbose_name': 'Волейбольная команда',
                'verbose_name_plural': 'Волейбольные команды',
            },
            bases=('SCSapp.team',),
        ),
        migrations.CreateModel(
            name='VolleyballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surename', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('trainer', models.BooleanField(default=False, null=True, verbose_name='Тренер')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCSapp.volleyballteam')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['surename', 'name'],
            },
        ),
    ]
