# Generated by Django 4.0.3 on 2022-10-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='abstractmatchteamresult',
            name='teamScore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volleyballmatchteamresult',
            name='firstRoundScore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volleyballmatchteamresult',
            name='secondRoundScore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volleyballmatchteamresult',
            name='thirdRoundScore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='participant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCSapp.abstractparticipant'),
        ),
    ]
