# Generated by Django 4.0.3 on 2022-10-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0002_abstractparticipant_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractparticipant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='abstractparticipant',
            name='name',
            field=models.CharField(default='ФСУ', max_length=64, verbose_name='Название'),
        ),
    ]
