# Generated by Django 4.1.6 on 2023-06-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0002_faculty_description_faculty_emblem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractmatch',
            name='competitionStage',
            field=models.CharField(choices=[('1/1', 'Финал'), ('1/2', 'Полуфинал'), ('1/4', '1/4-финал'), ('1/8', '1/8-финал')], max_length=16, null=True, verbose_name='Круг розыгрыша'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='dateTimeStartCompetition',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Заявки на участие принимаются до'),
        ),
    ]
