# Generated by Django 4.0.3 on 2022-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0003_alter_competition_protocol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchEvent',
            new_name='MatchAction',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competitionEndDateTime',
            new_name='_dateTimeFinishCompetition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='lastTimeForApplications',
            new_name='_dateTimeStartCompetition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='organizer',
            new_name='_organizer',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='protocol',
            new_name='_protocol',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='organizerName',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='theNumberOfTeamsRequiredToStartTheCompetition',
        ),
        migrations.AddField(
            model_name='competition',
            name='_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='competition',
            name='_isHightLevelSportEvent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='competition',
            name='_sportType',
            field=models.CharField(default='Волейбол', max_length=32, verbose_name='Тип спорта'),
        ),
        migrations.AddField(
            model_name='competition',
            name='_status',
            field=models.CharField(choices=[('AN', 'Анонсированное'), ('CR', 'Текущее'), ('P', 'Прошедшее')], default='AN', max_length=3),
        ),
    ]
