# Generated by Django 4.0.3 on 2022-10-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0003_alter_abstractparticipant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('Goal', 'Goal'), ('Player replacement', 'Player replacement'), ('Part', 'Part'), ('Interval', 'Interval'), ('Game over', 'Game over')], max_length=20)),
                ('Team', models.IntegerField(blank=True, choices=[(1, 'first'), (2, 'second')], null=True, verbose_name='Команда')),
                ('EventTime', models.TimeField(auto_now_add=True, verbose_name='Время события')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCSapp.abstractmatch', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
