# Generated by Django 4.0.3 on 2022-10-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0004_rename_matchevent_matchaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='_status',
            new_name='status',
        ),
    ]
