# Generated by Django 4.0.3 on 2022-10-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0005_rename__status_competition_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='status',
            new_name='_status',
        ),
    ]
