# Generated by Django 4.0.3 on 2022-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0006_rename_status_competition__status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='_type',
            field=models.CharField(choices=[('INT', 'Внутреннее'), ('IC', 'Межвузовское')], default='IC', max_length=3),
        ),
        migrations.AlterField(
            model_name='competition',
            name='_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='_sportType',
            field=models.CharField(choices=[('FB', 'Футбол'), ('VB', 'Волейбол')], default='VB', max_length=128, verbose_name='Тип спорта'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='_status',
            field=models.CharField(choices=[('AN', 'Анонсированное'), ('CR', 'Текущее'), ('P', 'Прошедшее')], default='AN', max_length=2, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='MatchAction',
        ),
    ]
