# Generated by Django 4.0.3 on 2022-10-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCSapp', '0007_abstractmatch_competition__type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='_dateTimeFinishCompetition',
            new_name='dateTimeFinishCompetition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_dateTimeStartCompetition',
            new_name='dateTimeStartCompetition',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_isHightLevelSportEvent',
            new_name='isHightLevelSportEvent',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_organizer',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_protocol',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_sportType',
            new_name='sportType',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='_type',
            new_name='type',
        ),
    ]
