# Generated by Django 4.1.6 on 2023-05-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SCSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=20, verbose_name='Тип события')),
                ('eventTime', models.TimeField(auto_now_add=True, verbose_name='Время события')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCSapp.abstractmatch', verbose_name='Матч')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCSapp.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
