# Generated by Django 4.1.6 on 2023-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchaction',
            name='additional_note',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Дополнительная JSON информация'),
        ),
    ]
