# Generated by Django 4.1.6 on 2023-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translationApp', '0002_matchaction_additional_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchaction',
            name='additional_note',
        ),
        migrations.AddField(
            model_name='matchaction',
            name='round',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
